// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See VopenMSP430.h for the primary calling header

#ifndef VERILATED_VOPENMSP430___024ROOT_H_
#define VERILATED_VOPENMSP430___024ROOT_H_  // guard

#include "verilated_heavy.h"

//==========

class VopenMSP430__Syms;

//----------

VL_MODULE(VopenMSP430___024root) {
  public:

    // PORTS
    VL_OUT8(puc_rst,0,0);
    VL_IN8(cpu_mclk,0,0);
    VL_IN8(dma_mclk,0,0);
    VL_IN8(dbg_clk,0,0);
    VL_IN8(dbg_rst,0,0);
    VL_IN8(por,0,0);
    VL_IN8(smclk,0,0);
    VL_OUT8(dbg_freeze,0,0);
    VL_OUT8(dbg_i2c_sda_out,0,0);
    VL_OUT8(dbg_uart_txd,0,0);
    VL_OUT8(dmem_cen,0,0);
    VL_OUT8(dmem_wen,1,0);
    VL_OUT8(mclk,0,0);
    VL_OUT8(dma_ready,0,0);
    VL_OUT8(dma_resp,0,0);
    VL_OUT8(per_en,0,0);
    VL_OUT8(per_we,1,0);
    VL_OUT8(pmem_cen,0,0);
    VL_OUT8(pmem_wen,1,0);
    VL_IN8(aclk,0,0);
    VL_IN8(aclk_en,0,0);
    VL_IN8(cpu_en_s,0,0);
    VL_IN8(dbg_en_s,0,0);
    VL_IN8(dco_enable,0,0);
    VL_IN8(per_dout,0,0);
    VL_IN8(puc_pnd_set,0,0);
    VL_IN8(smclk_en,0,0);
    VL_IN8(dbg_i2c_addr,6,0);
    VL_IN8(dbg_i2c_broadcast,6,0);
    VL_IN8(dbg_i2c_scl,0,0);
    VL_IN8(dbg_i2c_sda_in,0,0);
    VL_IN8(dbg_uart_rxd,0,0);
    VL_IN8(dma_en,0,0);
    VL_IN8(dma_priority,0,0);
    VL_IN8(dma_we,1,0);
    VL_IN8(dma_wkup,0,0);
    VL_IN8(nmi,0,0);
    VL_IN8(reset_n,0,0);
    VL_IN8(scan_enable,0,0);
    VL_IN8(scan_mode,0,0);
    VL_IN8(wkup,0,0);
    VL_OUT16(dmem_addr,8,0);
    VL_OUT16(dmem_din,15,0);
    VL_OUT16(irq_acc,13,0);
    VL_OUT16(dma_dout,15,0);
    VL_OUT16(per_addr,13,0);
    VL_OUT16(per_din,15,0);
    VL_OUT16(pmem_addr,10,0);
    VL_OUT16(pmem_din,15,0);
    VL_IN16(dmem_dout,15,0);
    VL_IN16(irq,13,0);
    VL_IN16(dma_addr,15,1);
    VL_IN16(dma_din,15,0);
    VL_IN16(pmem_dout,15,0);

    // LOCAL SIGNALS
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        CData/*0:0*/ openMSP430__DOT__frontend_0__DOT__mclk_irq_num;
        CData/*0:0*/ openMSP430__DOT__frontend_0__DOT__mclk_pc;
        CData/*0:0*/ openMSP430__DOT__frontend_0__DOT__mclk_inst_sext;
        CData/*0:0*/ openMSP430__DOT__frontend_0__DOT__mclk_inst_dext;
        CData/*0:0*/ openMSP430__DOT__frontend_0__DOT__mclk_decode;
        CData/*0:0*/ openMSP430__DOT__execution_unit_0__DOT__mclk_mdb_out_nxt;
        CData/*0:0*/ openMSP430__DOT__execution_unit_0__DOT__mclk_mdb_in_buf;
        CData/*0:0*/ openMSP430__DOT__execution_unit_0__DOT__register_file_0__DOT__mclk_r1;
        CData/*0:0*/ openMSP430__DOT__execution_unit_0__DOT__register_file_0__DOT__mclk_r2;
        CData/*0:0*/ openMSP430__DOT__execution_unit_0__DOT__register_file_0__DOT__mclk_r3;
        CData/*0:0*/ openMSP430__DOT__execution_unit_0__DOT__register_file_0__DOT__mclk_r4;
        CData/*0:0*/ openMSP430__DOT__execution_unit_0__DOT__register_file_0__DOT__mclk_r5;
        CData/*0:0*/ openMSP430__DOT__execution_unit_0__DOT__register_file_0__DOT__mclk_r6;
        CData/*0:0*/ openMSP430__DOT__execution_unit_0__DOT__register_file_0__DOT__mclk_r7;
        CData/*0:0*/ openMSP430__DOT__execution_unit_0__DOT__register_file_0__DOT__mclk_r8;
        CData/*0:0*/ openMSP430__DOT__execution_unit_0__DOT__register_file_0__DOT__mclk_r9;
        CData/*0:0*/ openMSP430__DOT__execution_unit_0__DOT__register_file_0__DOT__mclk_r10;
        CData/*0:0*/ openMSP430__DOT__execution_unit_0__DOT__register_file_0__DOT__mclk_r11;
        CData/*0:0*/ openMSP430__DOT__execution_unit_0__DOT__register_file_0__DOT__mclk_r12;
        CData/*0:0*/ openMSP430__DOT__execution_unit_0__DOT__register_file_0__DOT__mclk_r13;
        CData/*0:0*/ openMSP430__DOT__execution_unit_0__DOT__register_file_0__DOT__mclk_r14;
        CData/*0:0*/ openMSP430__DOT__execution_unit_0__DOT__register_file_0__DOT__mclk_r15;
        CData/*0:0*/ openMSP430__DOT__mem_backbone_0__DOT__mclk_bckup_gated;
        CData/*0:0*/ openMSP430__DOT__sfr_0__DOT__wakeup_cell_nmi__DOT__wkup_rst;
        CData/*0:0*/ openMSP430__DOT__sfr_0__DOT__wakeup_cell_nmi__DOT__wkup_clk;
        CData/*0:0*/ openMSP430__DOT__watchdog_0__DOT__mclk_wdtctl;
        CData/*0:0*/ openMSP430__DOT__watchdog_0__DOT__wdt_rst;
        CData/*0:0*/ openMSP430__DOT__watchdog_0__DOT__wdt_clk_cnt;
        CData/*0:0*/ openMSP430__DOT__watchdog_0__DOT__wakeup_cell_wdog__DOT__wkup_rst;
        CData/*0:0*/ openMSP430__DOT__watchdog_0__DOT__wakeup_cell_wdog__DOT__wkup_clk;
        CData/*0:0*/ openMSP430__DOT__multiplier_0__DOT__mclk_op1;
        CData/*0:0*/ openMSP430__DOT__multiplier_0__DOT__mclk_op2;
        CData/*0:0*/ openMSP430__DOT__multiplier_0__DOT__mclk_reslo;
        CData/*0:0*/ openMSP430__DOT__multiplier_0__DOT__mclk_reshi;
        CData/*7:0*/ openMSP430__DOT__inst_ad;
        CData/*7:0*/ openMSP430__DOT__inst_as;
        CData/*0:0*/ openMSP430__DOT__inst_bw;
        CData/*0:0*/ openMSP430__DOT__inst_irq_rst;
        CData/*0:0*/ openMSP430__DOT__inst_mov;
        CData/*7:0*/ openMSP430__DOT__inst_so;
        CData/*2:0*/ openMSP430__DOT__inst_type;
        CData/*7:0*/ openMSP430__DOT__inst_jmp;
        CData/*3:0*/ openMSP430__DOT__e_state;
        CData/*0:0*/ openMSP430__DOT__exec_done;
        CData/*0:0*/ openMSP430__DOT__decode_noirq;
        CData/*0:0*/ openMSP430__DOT__eu_mb_en;
        CData/*0:0*/ openMSP430__DOT__pc_sw_wr;
        CData/*0:0*/ openMSP430__DOT__nmi_pnd;
        CData/*0:0*/ openMSP430__DOT__wdtie;
        CData/*0:0*/ openMSP430__DOT__wdtifg;
        CData/*0:0*/ openMSP430__DOT__wdt_irq;
        CData/*0:0*/ openMSP430__DOT__dbg_mem_en;
        CData/*0:0*/ openMSP430__DOT__dbg_reg_wr;
        CData/*1:0*/ openMSP430__DOT__dbg_mem_wr;
        CData/*0:0*/ openMSP430__DOT__cpu_halt_st;
        CData/*2:0*/ openMSP430__DOT__frontend_0__DOT__i_state;
        CData/*2:0*/ openMSP430__DOT__frontend_0__DOT__i_state_nxt;
        CData/*1:0*/ openMSP430__DOT__frontend_0__DOT__inst_sz;
        CData/*1:0*/ openMSP430__DOT__frontend_0__DOT__inst_sz_nxt;
        CData/*0:0*/ openMSP430__DOT__frontend_0__DOT__irq_detect;
        CData/*2:0*/ openMSP430__DOT__frontend_0__DOT__inst_type_nxt;
        CData/*3:0*/ openMSP430__DOT__frontend_0__DOT__e_state_nxt;
        CData/*0:0*/ openMSP430__DOT__frontend_0__DOT__cpu_halt_req;
        CData/*0:0*/ openMSP430__DOT__frontend_0__DOT__decode;
    };
    struct {
        CData/*0:0*/ openMSP430__DOT__frontend_0__DOT__fetch;
        CData/*5:0*/ openMSP430__DOT__frontend_0__DOT__irq_num;
        CData/*0:0*/ openMSP430__DOT__frontend_0__DOT__pmem_busy;
        CData/*0:0*/ openMSP430__DOT__frontend_0__DOT__is_sext;
        CData/*0:0*/ openMSP430__DOT__frontend_0__DOT__inst_dext_rdy;
        CData/*7:0*/ openMSP430__DOT__frontend_0__DOT__inst_so_nxt;
        CData/*2:0*/ openMSP430__DOT__frontend_0__DOT__inst_jmp_bin;
        CData/*3:0*/ openMSP430__DOT__frontend_0__DOT__inst_dest_bin;
        CData/*3:0*/ openMSP430__DOT__frontend_0__DOT__inst_src_bin;
        CData/*7:0*/ openMSP430__DOT__frontend_0__DOT__inst_ad_nxt;
        CData/*0:0*/ openMSP430__DOT__frontend_0__DOT__exec_jmp;
        CData/*0:0*/ openMSP430__DOT__frontend_0__DOT__exec_dst_wr;
        CData/*0:0*/ openMSP430__DOT__frontend_0__DOT__exec_src_wr;
        CData/*0:0*/ openMSP430__DOT__frontend_0__DOT__exec_dext_rdy;
        CData/*3:0*/ openMSP430__DOT__frontend_0__DOT__e_first_state;
        CData/*0:0*/ openMSP430__DOT__frontend_0__DOT__clock_gate_irq_num__DOT__enable_latch;
        CData/*0:0*/ openMSP430__DOT__frontend_0__DOT__clock_gate_pc__DOT__enable_latch;
        CData/*0:0*/ openMSP430__DOT__frontend_0__DOT__clock_gate_inst_sext__DOT__enable_latch;
        CData/*0:0*/ openMSP430__DOT__frontend_0__DOT__clock_gate_inst_dext__DOT__enable_latch;
        CData/*0:0*/ openMSP430__DOT__frontend_0__DOT__clock_gate_decode__DOT__enable_latch;
        CData/*3:0*/ openMSP430__DOT__execution_unit_0__DOT__alu_stat;
        CData/*3:0*/ openMSP430__DOT__execution_unit_0__DOT__alu_stat_wr;
        CData/*3:0*/ openMSP430__DOT__execution_unit_0__DOT__status;
        CData/*0:0*/ openMSP430__DOT__execution_unit_0__DOT__reg_dest_wr;
        CData/*0:0*/ openMSP430__DOT__execution_unit_0__DOT__reg_sp_wr;
        CData/*0:0*/ openMSP430__DOT__execution_unit_0__DOT__reg_incr;
        CData/*0:0*/ openMSP430__DOT__execution_unit_0__DOT__mb_wr_det;
        CData/*0:0*/ openMSP430__DOT__execution_unit_0__DOT__mab_lsb;
        CData/*0:0*/ openMSP430__DOT__execution_unit_0__DOT__mdb_in_buf_en;
        CData/*0:0*/ openMSP430__DOT__execution_unit_0__DOT__mdb_in_buf_valid;
        CData/*0:0*/ openMSP430__DOT__execution_unit_0__DOT__register_file_0__DOT__r1_wr;
        CData/*0:0*/ openMSP430__DOT__execution_unit_0__DOT__register_file_0__DOT__r2_wr;
        CData/*4:0*/ openMSP430__DOT__execution_unit_0__DOT__register_file_0__DOT__r2_nxt;
        CData/*0:0*/ openMSP430__DOT__execution_unit_0__DOT__register_file_0__DOT__r4_wr;
        CData/*0:0*/ openMSP430__DOT__execution_unit_0__DOT__register_file_0__DOT__r5_wr;
        CData/*0:0*/ openMSP430__DOT__execution_unit_0__DOT__register_file_0__DOT__r6_wr;
        CData/*0:0*/ openMSP430__DOT__execution_unit_0__DOT__register_file_0__DOT__r7_wr;
        CData/*0:0*/ openMSP430__DOT__execution_unit_0__DOT__register_file_0__DOT__r8_wr;
        CData/*0:0*/ openMSP430__DOT__execution_unit_0__DOT__register_file_0__DOT__r9_wr;
        CData/*0:0*/ openMSP430__DOT__execution_unit_0__DOT__register_file_0__DOT__r10_wr;
        CData/*0:0*/ openMSP430__DOT__execution_unit_0__DOT__register_file_0__DOT__r11_wr;
        CData/*0:0*/ openMSP430__DOT__execution_unit_0__DOT__register_file_0__DOT__r12_wr;
        CData/*0:0*/ openMSP430__DOT__execution_unit_0__DOT__register_file_0__DOT__r13_wr;
        CData/*0:0*/ openMSP430__DOT__execution_unit_0__DOT__register_file_0__DOT__r14_wr;
        CData/*0:0*/ openMSP430__DOT__execution_unit_0__DOT__register_file_0__DOT__r15_wr;
        CData/*0:0*/ openMSP430__DOT__execution_unit_0__DOT__register_file_0__DOT__clock_gate_r1__DOT__enable_latch;
        CData/*0:0*/ openMSP430__DOT__execution_unit_0__DOT__register_file_0__DOT__clock_gate_r2__DOT__enable_latch;
        CData/*0:0*/ openMSP430__DOT__execution_unit_0__DOT__register_file_0__DOT__clock_gate_r3__DOT__enable_latch;
        CData/*0:0*/ openMSP430__DOT__execution_unit_0__DOT__register_file_0__DOT__clock_gate_r4__DOT__enable_latch;
        CData/*0:0*/ openMSP430__DOT__execution_unit_0__DOT__register_file_0__DOT__clock_gate_r5__DOT__enable_latch;
        CData/*0:0*/ openMSP430__DOT__execution_unit_0__DOT__register_file_0__DOT__clock_gate_r6__DOT__enable_latch;
        CData/*0:0*/ openMSP430__DOT__execution_unit_0__DOT__register_file_0__DOT__clock_gate_r7__DOT__enable_latch;
        CData/*0:0*/ openMSP430__DOT__execution_unit_0__DOT__register_file_0__DOT__clock_gate_r8__DOT__enable_latch;
        CData/*0:0*/ openMSP430__DOT__execution_unit_0__DOT__register_file_0__DOT__clock_gate_r9__DOT__enable_latch;
        CData/*0:0*/ openMSP430__DOT__execution_unit_0__DOT__register_file_0__DOT__clock_gate_r10__DOT__enable_latch;
        CData/*0:0*/ openMSP430__DOT__execution_unit_0__DOT__register_file_0__DOT__clock_gate_r11__DOT__enable_latch;
        CData/*0:0*/ openMSP430__DOT__execution_unit_0__DOT__register_file_0__DOT__clock_gate_r12__DOT__enable_latch;
        CData/*0:0*/ openMSP430__DOT__execution_unit_0__DOT__register_file_0__DOT__clock_gate_r13__DOT__enable_latch;
        CData/*0:0*/ openMSP430__DOT__execution_unit_0__DOT__register_file_0__DOT__clock_gate_r14__DOT__enable_latch;
        CData/*0:0*/ openMSP430__DOT__execution_unit_0__DOT__register_file_0__DOT__clock_gate_r15__DOT__enable_latch;
        CData/*0:0*/ openMSP430__DOT__execution_unit_0__DOT__alu_0__DOT__op_bit8_msk;
        CData/*0:0*/ openMSP430__DOT__execution_unit_0__DOT__clock_gate_mdb_out_nxt__DOT__enable_latch;
        CData/*0:0*/ openMSP430__DOT__execution_unit_0__DOT__clock_gate_mdb_in_buf__DOT__enable_latch;
        CData/*0:0*/ openMSP430__DOT__mem_backbone_0__DOT__ext_mem_en;
    };
    struct {
        CData/*0:0*/ openMSP430__DOT__mem_backbone_0__DOT__ext_dmem_sel;
        CData/*0:0*/ openMSP430__DOT__mem_backbone_0__DOT__ext_dmem_en;
        CData/*0:0*/ openMSP430__DOT__mem_backbone_0__DOT__ext_pmem_en;
        CData/*0:0*/ openMSP430__DOT__mem_backbone_0__DOT__ext_per_en;
        CData/*0:0*/ openMSP430__DOT__mem_backbone_0__DOT__dma_ready_dly;
        CData/*1:0*/ openMSP430__DOT__mem_backbone_0__DOT__ext_mem_wr;
        CData/*0:0*/ openMSP430__DOT__mem_backbone_0__DOT__eu_pmem_en;
        CData/*0:0*/ openMSP430__DOT__mem_backbone_0__DOT__fe_pmem_en;
        CData/*0:0*/ openMSP430__DOT__mem_backbone_0__DOT__eu_per_en;
        CData/*0:0*/ openMSP430__DOT__mem_backbone_0__DOT__fe_pmem_en_dly;
        CData/*0:0*/ openMSP430__DOT__mem_backbone_0__DOT__fe_pmem_save;
        CData/*0:0*/ openMSP430__DOT__mem_backbone_0__DOT__pmem_dout_bckup_sel;
        CData/*1:0*/ openMSP430__DOT__mem_backbone_0__DOT__eu_mdb_in_sel;
        CData/*1:0*/ openMSP430__DOT__mem_backbone_0__DOT__ext_mem_din_sel;
        CData/*0:0*/ openMSP430__DOT__mem_backbone_0__DOT__clock_gate_bckup__DOT__enable_latch;
        CData/*0:0*/ openMSP430__DOT__sfr_0__DOT__nmie;
        CData/*0:0*/ openMSP430__DOT__sfr_0__DOT__nmiifg;
        CData/*0:0*/ openMSP430__DOT__sfr_0__DOT__nmi_capture_rst;
        CData/*0:0*/ openMSP430__DOT__sfr_0__DOT__nmi_capture;
        CData/*0:0*/ openMSP430__DOT__sfr_0__DOT__nmi_dly;
        CData/*1:0*/ openMSP430__DOT__sfr_0__DOT__sync_cell_nmi__DOT__data_sync;
        CData/*0:0*/ openMSP430__DOT__watchdog_0__DOT__reg_sel;
        CData/*3:0*/ openMSP430__DOT__watchdog_0__DOT__reg_wr;
        CData/*7:0*/ openMSP430__DOT__watchdog_0__DOT__wdtctl;
        CData/*0:0*/ openMSP430__DOT__watchdog_0__DOT__wdtcnt_clr_toggle;
        CData/*0:0*/ openMSP430__DOT__watchdog_0__DOT__wdtcnt_clr_sync_dly;
        CData/*0:0*/ openMSP430__DOT__watchdog_0__DOT__wdtqn_edge;
        CData/*0:0*/ openMSP430__DOT__watchdog_0__DOT__wdtcnt_clr;
        CData/*1:0*/ openMSP430__DOT__watchdog_0__DOT__wdtisx_s;
        CData/*1:0*/ openMSP430__DOT__watchdog_0__DOT__wdtisx_ss;
        CData/*0:0*/ openMSP430__DOT__watchdog_0__DOT__wdt_evt_toggle;
        CData/*0:0*/ openMSP430__DOT__watchdog_0__DOT__wdt_evt_toggle_sync_dly;
        CData/*0:0*/ openMSP430__DOT__watchdog_0__DOT__wdtifg_clr_reg;
        CData/*0:0*/ openMSP430__DOT__watchdog_0__DOT__wdtifg_clr;
        CData/*0:0*/ openMSP430__DOT__watchdog_0__DOT__wdtqn_edge_reg;
        CData/*0:0*/ openMSP430__DOT__watchdog_0__DOT__wdtifg_set;
        CData/*0:0*/ openMSP430__DOT__watchdog_0__DOT__clock_gate_wdtctl__DOT__enable_latch;
        CData/*1:0*/ openMSP430__DOT__watchdog_0__DOT__sync_reset_por__DOT__data_sync;
        CData/*1:0*/ openMSP430__DOT__watchdog_0__DOT__sync_cell_wdtcnt_clr__DOT__data_sync;
        CData/*1:0*/ openMSP430__DOT__watchdog_0__DOT__sync_cell_wdtcnt_incr__DOT__data_sync;
        CData/*0:0*/ openMSP430__DOT__watchdog_0__DOT__clock_gate_wdtcnt__DOT__enable_latch;
        CData/*1:0*/ openMSP430__DOT__watchdog_0__DOT__sync_cell_wdt_evt__DOT__data_sync;
        CData/*0:0*/ openMSP430__DOT__multiplier_0__DOT__result_clr;
        CData/*1:0*/ openMSP430__DOT__multiplier_0__DOT__sumext_s;
        CData/*1:0*/ openMSP430__DOT__multiplier_0__DOT__sumext_s_nxt;
        CData/*0:0*/ openMSP430__DOT__multiplier_0__DOT__sign_sel;
        CData/*0:0*/ openMSP430__DOT__multiplier_0__DOT__acc_sel;
        CData/*1:0*/ openMSP430__DOT__multiplier_0__DOT__cycle;
        CData/*0:0*/ openMSP430__DOT__multiplier_0__DOT__clock_gate_op1__DOT__enable_latch;
        CData/*0:0*/ openMSP430__DOT__multiplier_0__DOT__clock_gate_op2__DOT__enable_latch;
        CData/*0:0*/ openMSP430__DOT__multiplier_0__DOT__clock_gate_reslo__DOT__enable_latch;
        CData/*0:0*/ openMSP430__DOT__multiplier_0__DOT__clock_gate_reshi__DOT__enable_latch;
        CData/*5:0*/ openMSP430__DOT__dbg_0__DOT__dbg_addr;
        CData/*0:0*/ openMSP430__DOT__dbg_0__DOT__dbg_wr;
        CData/*0:0*/ openMSP430__DOT__dbg_0__DOT__mem_burst;
        CData/*0:0*/ openMSP430__DOT__dbg_0__DOT__dbg_reg_rd;
        CData/*0:0*/ openMSP430__DOT__dbg_0__DOT__dbg_mem_rd_dly;
        CData/*0:0*/ openMSP430__DOT__dbg_0__DOT__dbg_swbrk;
        CData/*0:0*/ openMSP430__DOT__dbg_0__DOT__dbg_rd;
        CData/*0:0*/ openMSP430__DOT__dbg_0__DOT__dbg_rd_rdy;
        CData/*0:0*/ openMSP430__DOT__dbg_0__DOT__mem_burst_rd;
        CData/*0:0*/ openMSP430__DOT__dbg_0__DOT__mem_burst_wr;
        CData/*3:0*/ openMSP430__DOT__dbg_0__DOT__cpu_ctl;
        CData/*1:0*/ openMSP430__DOT__dbg_0__DOT__cpu_stat;
    };
    struct {
        CData/*1:0*/ openMSP430__DOT__dbg_0__DOT__cpu_stat_set;
        CData/*2:0*/ openMSP430__DOT__dbg_0__DOT__mem_ctl;
        CData/*0:0*/ openMSP430__DOT__dbg_0__DOT__mem_start;
        CData/*0:0*/ openMSP430__DOT__dbg_0__DOT__dbg_mem_acc;
        CData/*0:0*/ openMSP430__DOT__dbg_0__DOT__dbg_reg_acc;
        CData/*1:0*/ openMSP430__DOT__dbg_0__DOT__inc_step;
        CData/*0:0*/ openMSP430__DOT__dbg_0__DOT__halt_flag;
        CData/*0:0*/ openMSP430__DOT__dbg_0__DOT__halt_flag_set;
        CData/*0:0*/ openMSP430__DOT__dbg_0__DOT__mem_burst_start;
        CData/*0:0*/ openMSP430__DOT__dbg_0__DOT__mem_burst_end;
        CData/*0:0*/ openMSP430__DOT__dbg_0__DOT__mem_startb;
        CData/*1:0*/ openMSP430__DOT__dbg_0__DOT__mem_state;
        CData/*1:0*/ openMSP430__DOT__dbg_0__DOT__mem_state_nxt;
        CData/*4:0*/ openMSP430__DOT__dbg_0__DOT__dbg_hwbr_0__DOT__brk_ctl;
        CData/*5:0*/ openMSP430__DOT__dbg_0__DOT__dbg_hwbr_0__DOT__brk_stat;
        CData/*5:0*/ openMSP430__DOT__dbg_0__DOT__dbg_hwbr_0__DOT__brk_stat_set;
        CData/*1:0*/ openMSP430__DOT__dbg_0__DOT__dbg_uart_0__DOT__rxd_buf;
        CData/*0:0*/ openMSP430__DOT__dbg_0__DOT__dbg_uart_0__DOT__rxd_maj;
        CData/*0:0*/ openMSP430__DOT__dbg_0__DOT__dbg_uart_0__DOT__rxd_maj_nxt;
        CData/*0:0*/ openMSP430__DOT__dbg_0__DOT__dbg_uart_0__DOT__rxd_fe;
        CData/*0:0*/ openMSP430__DOT__dbg_0__DOT__dbg_uart_0__DOT__rxd_re;
        CData/*2:0*/ openMSP430__DOT__dbg_0__DOT__dbg_uart_0__DOT__uart_state;
        CData/*2:0*/ openMSP430__DOT__dbg_0__DOT__dbg_uart_0__DOT__uart_state_nxt;
        CData/*0:0*/ openMSP430__DOT__dbg_0__DOT__dbg_uart_0__DOT__sync_done;
        CData/*0:0*/ openMSP430__DOT__dbg_0__DOT__dbg_uart_0__DOT__xfer_done;
        CData/*0:0*/ openMSP430__DOT__dbg_0__DOT__dbg_uart_0__DOT__cmd_valid;
        CData/*0:0*/ openMSP430__DOT__dbg_0__DOT__dbg_uart_0__DOT__rx_active;
        CData/*0:0*/ openMSP430__DOT__dbg_0__DOT__dbg_uart_0__DOT__sync_busy;
        CData/*3:0*/ openMSP430__DOT__dbg_0__DOT__dbg_uart_0__DOT__xfer_bit;
        CData/*0:0*/ openMSP430__DOT__dbg_0__DOT__dbg_uart_0__DOT__txd_start;
        CData/*0:0*/ openMSP430__DOT__dbg_0__DOT__dbg_uart_0__DOT__rxd_start;
        CData/*0:0*/ openMSP430__DOT__dbg_0__DOT__dbg_uart_0__DOT__xfer_bit_inc;
        CData/*0:0*/ openMSP430__DOT__dbg_0__DOT__dbg_uart_0__DOT__dbg_bw;
        CData/*1:0*/ openMSP430__DOT__dbg_0__DOT__dbg_uart_0__DOT__sync_cell_uart_rxd__DOT__data_sync;
        SData/*11:0*/ openMSP430__DOT__inst_alu;
        SData/*15:0*/ openMSP430__DOT__inst_dest;
        SData/*15:0*/ openMSP430__DOT__inst_dext;
        SData/*15:0*/ openMSP430__DOT__inst_sext;
        SData/*15:0*/ openMSP430__DOT__inst_src;
        SData/*15:0*/ openMSP430__DOT__eu_mdb_in;
        SData/*15:0*/ openMSP430__DOT__eu_mdb_out;
        SData/*15:0*/ openMSP430__DOT__fe_mdb_in;
        SData/*15:0*/ openMSP430__DOT__pc;
        SData/*15:0*/ openMSP430__DOT__pc_nxt;
        SData/*15:0*/ openMSP430__DOT__dbg_mem_dout;
        SData/*15:0*/ openMSP430__DOT__per_dout_clk;
        SData/*15:0*/ openMSP430__DOT__frontend_0__DOT__ext_nxt;
        SData/*15:0*/ openMSP430__DOT__frontend_0__DOT__inst_to_1hot;
        SData/*12:0*/ openMSP430__DOT__frontend_0__DOT__inst_as_nxt;
        SData/*11:0*/ openMSP430__DOT__frontend_0__DOT__inst_alu_nxt;
        SData/*15:0*/ openMSP430__DOT__execution_unit_0__DOT__reg_dest;
        SData/*15:0*/ openMSP430__DOT__execution_unit_0__DOT__mdb_in_bw;
        SData/*15:0*/ openMSP430__DOT__execution_unit_0__DOT__mdb_out_nxt;
        SData/*15:0*/ openMSP430__DOT__execution_unit_0__DOT__mdb_in_buf;
        SData/*15:0*/ openMSP430__DOT__execution_unit_0__DOT__register_file_0__DOT__inst_src_in;
        SData/*15:0*/ openMSP430__DOT__execution_unit_0__DOT__register_file_0__DOT__reg_incr_val;
        SData/*15:0*/ openMSP430__DOT__execution_unit_0__DOT__register_file_0__DOT__reg_dest_val_in;
        SData/*15:0*/ openMSP430__DOT__execution_unit_0__DOT__register_file_0__DOT__r1;
        SData/*15:0*/ openMSP430__DOT__execution_unit_0__DOT__register_file_0__DOT__r2;
        SData/*15:0*/ openMSP430__DOT__execution_unit_0__DOT__register_file_0__DOT__r3;
        SData/*15:0*/ openMSP430__DOT__execution_unit_0__DOT__register_file_0__DOT__r4;
        SData/*15:0*/ openMSP430__DOT__execution_unit_0__DOT__register_file_0__DOT__r5;
        SData/*15:0*/ openMSP430__DOT__execution_unit_0__DOT__register_file_0__DOT__r6;
        SData/*15:0*/ openMSP430__DOT__execution_unit_0__DOT__register_file_0__DOT__r7;
    };
    struct {
        SData/*15:0*/ openMSP430__DOT__execution_unit_0__DOT__register_file_0__DOT__r8;
        SData/*15:0*/ openMSP430__DOT__execution_unit_0__DOT__register_file_0__DOT__r9;
        SData/*15:0*/ openMSP430__DOT__execution_unit_0__DOT__register_file_0__DOT__r10;
        SData/*15:0*/ openMSP430__DOT__execution_unit_0__DOT__register_file_0__DOT__r11;
        SData/*15:0*/ openMSP430__DOT__execution_unit_0__DOT__register_file_0__DOT__r12;
        SData/*15:0*/ openMSP430__DOT__execution_unit_0__DOT__register_file_0__DOT__r13;
        SData/*15:0*/ openMSP430__DOT__execution_unit_0__DOT__register_file_0__DOT__r14;
        SData/*15:0*/ openMSP430__DOT__execution_unit_0__DOT__register_file_0__DOT__r15;
        SData/*15:0*/ openMSP430__DOT__mem_backbone_0__DOT__ext_mem_din;
        SData/*14:0*/ openMSP430__DOT__mem_backbone_0__DOT__ext_mem_addr;
        SData/*15:0*/ openMSP430__DOT__mem_backbone_0__DOT__ext_mem_dout;
        SData/*15:0*/ openMSP430__DOT__mem_backbone_0__DOT__per_dout_val;
        SData/*15:0*/ openMSP430__DOT__mem_backbone_0__DOT__pmem_dout_bckup;
        SData/*15:0*/ openMSP430__DOT__sfr_0__DOT__reg_lo_wr;
        SData/*15:0*/ openMSP430__DOT__sfr_0__DOT__reg_rd;
        SData/*15:0*/ openMSP430__DOT__watchdog_0__DOT__wdtcnt;
        SData/*15:0*/ openMSP430__DOT__watchdog_0__DOT__wdtcnt_nxt;
        SData/*15:0*/ openMSP430__DOT__multiplier_0__DOT__reg_wr;
        SData/*15:0*/ openMSP430__DOT__multiplier_0__DOT__reg_rd;
        SData/*15:0*/ openMSP430__DOT__multiplier_0__DOT__per_din_msk;
        SData/*15:0*/ openMSP430__DOT__multiplier_0__DOT__op1;
        SData/*15:0*/ openMSP430__DOT__multiplier_0__DOT__op2;
        SData/*15:0*/ openMSP430__DOT__multiplier_0__DOT__reslo;
        SData/*15:0*/ openMSP430__DOT__multiplier_0__DOT__reshi;
        SData/*15:0*/ openMSP430__DOT__dbg_0__DOT__dbg_din;
        SData/*15:0*/ openMSP430__DOT__dbg_0__DOT__mem_data;
        SData/*15:0*/ openMSP430__DOT__dbg_0__DOT__mem_addr;
        SData/*15:0*/ openMSP430__DOT__dbg_0__DOT__mem_cnt;
        SData/*15:0*/ openMSP430__DOT__dbg_0__DOT__mem_cnt_dec;
        SData/*15:0*/ openMSP430__DOT__dbg_0__DOT__dbg_dout;
        SData/*15:0*/ openMSP430__DOT__dbg_0__DOT__dbg_hwbr_0__DOT__brk_addr0;
        SData/*15:0*/ openMSP430__DOT__dbg_0__DOT__dbg_hwbr_0__DOT__brk_addr1;
        SData/*15:0*/ openMSP430__DOT__dbg_0__DOT__dbg_uart_0__DOT__xfer_cnt;
        IData/*16:0*/ openMSP430__DOT__execution_unit_0__DOT__alu_0__DOT__alu_add;
        IData/*16:0*/ openMSP430__DOT__execution_unit_0__DOT__alu_0__DOT__alu_out_nxt;
        IData/*25:0*/ openMSP430__DOT__multiplier_0__DOT__product;
        IData/*24:0*/ openMSP430__DOT__dbg_0__DOT__reg_dec;
        IData/*24:0*/ openMSP430__DOT__dbg_0__DOT__reg_wr;
        IData/*19:0*/ openMSP430__DOT__dbg_0__DOT__dbg_uart_0__DOT__xfer_buf;
        IData/*19:0*/ openMSP430__DOT__dbg_0__DOT__dbg_uart_0__DOT__xfer_buf_nxt;
        IData/*18:0*/ openMSP430__DOT__dbg_0__DOT__dbg_uart_0__DOT__sync_cnt;
        QData/*63:0*/ openMSP430__DOT__frontend_0__DOT__irq_acc_all;
        QData/*32:0*/ openMSP430__DOT__multiplier_0__DOT__result_nxt;
    };

    // LOCAL VARIABLES
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        CData/*0:0*/ __VinpClk__TOP__openMSP430__DOT__watchdog_0__DOT__wdt_rst;
        CData/*0:0*/ __VinpClk__TOP__openMSP430__DOT__sfr_0__DOT__wakeup_cell_nmi__DOT__wkup_rst;
        CData/*0:0*/ __Vclklast__TOP____VinpClk__TOP__openMSP430__DOT__watchdog_0__DOT__wdt_rst;
        CData/*0:0*/ __Vclklast__TOP__smclk;
        CData/*0:0*/ __Vclklast__TOP__dma_mclk;
        CData/*0:0*/ __Vclklast__TOP__por;
        CData/*0:0*/ __Vclklast__TOP__puc_rst;
        CData/*0:0*/ __Vclklast__TOP__dbg_clk;
        CData/*0:0*/ __Vclklast__TOP__dbg_rst;
        CData/*0:0*/ __Vclklast__TOP__cpu_mclk;
        CData/*0:0*/ __Vclklast__TOP__openMSP430__DOT__multiplier_0__DOT__mclk_reslo;
        CData/*0:0*/ __Vclklast__TOP__openMSP430__DOT__multiplier_0__DOT__mclk_reshi;
        CData/*0:0*/ __Vclklast__TOP__openMSP430__DOT__execution_unit_0__DOT__register_file_0__DOT__mclk_r4;
        CData/*0:0*/ __Vclklast__TOP__openMSP430__DOT__execution_unit_0__DOT__register_file_0__DOT__mclk_r5;
        CData/*0:0*/ __Vclklast__TOP__openMSP430__DOT__execution_unit_0__DOT__register_file_0__DOT__mclk_r6;
        CData/*0:0*/ __Vclklast__TOP__openMSP430__DOT__execution_unit_0__DOT__register_file_0__DOT__mclk_r7;
        CData/*0:0*/ __Vclklast__TOP__openMSP430__DOT__execution_unit_0__DOT__register_file_0__DOT__mclk_r8;
        CData/*0:0*/ __Vclklast__TOP__openMSP430__DOT__execution_unit_0__DOT__register_file_0__DOT__mclk_r9;
        CData/*0:0*/ __Vclklast__TOP__openMSP430__DOT__execution_unit_0__DOT__register_file_0__DOT__mclk_r10;
        CData/*0:0*/ __Vclklast__TOP__openMSP430__DOT__execution_unit_0__DOT__register_file_0__DOT__mclk_r11;
        CData/*0:0*/ __Vclklast__TOP__openMSP430__DOT__execution_unit_0__DOT__register_file_0__DOT__mclk_r12;
        CData/*0:0*/ __Vclklast__TOP__openMSP430__DOT__execution_unit_0__DOT__register_file_0__DOT__mclk_r13;
        CData/*0:0*/ __Vclklast__TOP__openMSP430__DOT__execution_unit_0__DOT__register_file_0__DOT__mclk_r14;
        CData/*0:0*/ __Vclklast__TOP__openMSP430__DOT__execution_unit_0__DOT__register_file_0__DOT__mclk_r15;
        CData/*0:0*/ __Vclklast__TOP__openMSP430__DOT__execution_unit_0__DOT__register_file_0__DOT__mclk_r1;
        CData/*0:0*/ __Vclklast__TOP__openMSP430__DOT__frontend_0__DOT__mclk_inst_sext;
        CData/*0:0*/ __Vclklast__TOP__openMSP430__DOT__multiplier_0__DOT__mclk_op2;
        CData/*0:0*/ __Vclklast__TOP__openMSP430__DOT__multiplier_0__DOT__mclk_op1;
        CData/*0:0*/ __Vclklast__TOP__openMSP430__DOT__frontend_0__DOT__mclk_irq_num;
        CData/*0:0*/ __Vclklast__TOP__openMSP430__DOT__watchdog_0__DOT__wdt_clk_cnt;
        CData/*0:0*/ __Vclklast__TOP__openMSP430__DOT__execution_unit_0__DOT__mclk_mdb_in_buf;
        CData/*0:0*/ __Vclklast__TOP__openMSP430__DOT__frontend_0__DOT__mclk_decode;
        CData/*0:0*/ __Vclklast__TOP__openMSP430__DOT__watchdog_0__DOT__wakeup_cell_wdog__DOT__wkup_clk;
        CData/*0:0*/ __Vclklast__TOP__openMSP430__DOT__watchdog_0__DOT__wakeup_cell_wdog__DOT__wkup_rst;
        CData/*0:0*/ __Vclklast__TOP__openMSP430__DOT__execution_unit_0__DOT__mclk_mdb_out_nxt;
        CData/*0:0*/ __Vclklast__TOP__openMSP430__DOT__frontend_0__DOT__mclk_inst_dext;
        CData/*0:0*/ __Vclklast__TOP__openMSP430__DOT__execution_unit_0__DOT__register_file_0__DOT__mclk_r3;
        CData/*0:0*/ __Vclklast__TOP__openMSP430__DOT__execution_unit_0__DOT__register_file_0__DOT__mclk_r2;
        CData/*0:0*/ __Vclklast__TOP__openMSP430__DOT__watchdog_0__DOT__mclk_wdtctl;
        CData/*0:0*/ __Vclklast__TOP__openMSP430__DOT__sfr_0__DOT__wakeup_cell_nmi__DOT__wkup_clk;
        CData/*0:0*/ __Vclklast__TOP____VinpClk__TOP__openMSP430__DOT__sfr_0__DOT__wakeup_cell_nmi__DOT__wkup_rst;
        CData/*0:0*/ __Vclklast__TOP__openMSP430__DOT__frontend_0__DOT__mclk_pc;
        CData/*0:0*/ __Vclklast__TOP__openMSP430__DOT__mem_backbone_0__DOT__mclk_bckup_gated;
        CData/*3:0*/ __Vchglast__TOP__openMSP430__DOT__e_state;
        CData/*0:0*/ __Vchglast__TOP__openMSP430__DOT__frontend_0__DOT__irq_detect;
        CData/*0:0*/ __Vchglast__TOP__openMSP430__DOT__frontend_0__DOT__clock_gate_inst_sext__DOT__enable_latch;
        CData/*3:0*/ __Vchglast__TOP__openMSP430__DOT__execution_unit_0__DOT__alu_stat_wr;
        CData/*0:0*/ __Vchglast__TOP__openMSP430__DOT__execution_unit_0__DOT__register_file_0__DOT__clock_gate_r1__DOT__enable_latch;
        CData/*0:0*/ __Vchglast__TOP__openMSP430__DOT__execution_unit_0__DOT__register_file_0__DOT__clock_gate_r4__DOT__enable_latch;
        CData/*0:0*/ __Vchglast__TOP__openMSP430__DOT__execution_unit_0__DOT__register_file_0__DOT__clock_gate_r5__DOT__enable_latch;
        CData/*0:0*/ __Vchglast__TOP__openMSP430__DOT__execution_unit_0__DOT__register_file_0__DOT__clock_gate_r6__DOT__enable_latch;
        CData/*0:0*/ __Vchglast__TOP__openMSP430__DOT__execution_unit_0__DOT__register_file_0__DOT__clock_gate_r7__DOT__enable_latch;
        CData/*0:0*/ __Vchglast__TOP__openMSP430__DOT__execution_unit_0__DOT__register_file_0__DOT__clock_gate_r8__DOT__enable_latch;
        CData/*0:0*/ __Vchglast__TOP__openMSP430__DOT__execution_unit_0__DOT__register_file_0__DOT__clock_gate_r9__DOT__enable_latch;
        CData/*0:0*/ __Vchglast__TOP__openMSP430__DOT__execution_unit_0__DOT__register_file_0__DOT__clock_gate_r10__DOT__enable_latch;
        CData/*0:0*/ __Vchglast__TOP__openMSP430__DOT__execution_unit_0__DOT__register_file_0__DOT__clock_gate_r11__DOT__enable_latch;
        CData/*0:0*/ __Vchglast__TOP__openMSP430__DOT__execution_unit_0__DOT__register_file_0__DOT__clock_gate_r12__DOT__enable_latch;
        CData/*0:0*/ __Vchglast__TOP__openMSP430__DOT__execution_unit_0__DOT__register_file_0__DOT__clock_gate_r13__DOT__enable_latch;
        CData/*0:0*/ __Vchglast__TOP__openMSP430__DOT__execution_unit_0__DOT__register_file_0__DOT__clock_gate_r14__DOT__enable_latch;
        CData/*0:0*/ __Vchglast__TOP__openMSP430__DOT__execution_unit_0__DOT__register_file_0__DOT__clock_gate_r15__DOT__enable_latch;
        CData/*0:0*/ __Vchglast__TOP__openMSP430__DOT__sfr_0__DOT__wakeup_cell_nmi__DOT__wkup_rst;
        CData/*0:0*/ __Vchglast__TOP__openMSP430__DOT__watchdog_0__DOT__wdt_rst;
        CData/*0:0*/ __Vchglast__TOP__openMSP430__DOT__watchdog_0__DOT__wdtcnt_clr;
        CData/*0:0*/ __Vchglast__TOP__openMSP430__DOT__multiplier_0__DOT__clock_gate_reslo__DOT__enable_latch;
    };
    struct {
        CData/*0:0*/ __Vchglast__TOP__openMSP430__DOT__multiplier_0__DOT__clock_gate_reshi__DOT__enable_latch;
        SData/*15:0*/ __Vchglast__TOP__openMSP430__DOT__fe_mdb_in;
        SData/*15:0*/ __Vchglast__TOP__openMSP430__DOT__pc;
        SData/*15:0*/ __Vchglast__TOP__openMSP430__DOT__multiplier_0__DOT__reg_wr;
    };

    // INTERNAL VARIABLES
    VopenMSP430__Syms* vlSymsp;  // Symbol table

    // CONSTRUCTORS
  private:
    VL_UNCOPYABLE(VopenMSP430___024root);  ///< Copying not allowed
  public:
    VopenMSP430___024root(const char* name);
    ~VopenMSP430___024root();

    // INTERNAL METHODS
    void __Vconfigure(VopenMSP430__Syms* symsp, bool first);
} VL_ATTR_ALIGNED(VL_CACHE_LINE_BYTES);

//----------


#endif  // guard
